board/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('races/', views.races_list, name='races'),
    path('accounts/register', views.register, name='register'),
    path('races/<uuid:id>', views.race_detail, name='race-detail')
]

scoreboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('board.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/main/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('board.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/main/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Racer(models.Model):
    EXP_RACER = (
        ('B', 'Beginner'),
        ('I', 'Intermediate'),
        ('E', 'Experienced'),
        ('P', 'Professional'),
    )
    
    CLASS_RACER = (
        ('4', 'Fourth'),
        ('3', 'Third'),
        ('2', 'Second'),
        ('1', 'First'),
    )

    id = models.UUIDField('Identifier', primary_key=True, default=uuid.uuid4, editable=False)
    name_r = models.CharField('Name', max_length=200, help_text='Enter the racer\'s name')
    name_t = models.CharField('Team', max_length=200, help_text='Enter the team\'s name')
    desc_c = models.CharField('Car', max_length=1000, help_text='Enter the car\'s description')
    desc_r = models.CharField('Description', max_length=1000, help_text='Enter the racer\'s description')
    exp_r = models.CharField(
        'Experience',
        max_length=1,
        choices=EXP_RACER,
        blank=False,
        default='B',
        help_text='Choose the racer\'s experience'
    )
    class_r = models.CharField(
        'Class',
        max_length=1,
        choices=CLASS_RACER,
        blank=False,
        default='4',
        help_text='Choose the racer\'s class'
    )

    def __str__(self):
        return self.name_r


class Race(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    first = models.ForeignKey('Racer', related_name='racer_first', on_delete=models.SET_NULL, null=True) 
    second = models.ForeignKey('Racer', related_name='racer_second', on_delete=models.SET_NULL, null=True) 
    third = models.ForeignKey('Racer', related_name='racer_third', on_delete=models.SET_NULL, null=True) 
    fourth = models.ForeignKey('Racer', related_name='racer_fourth', on_delete=models.SET_NULL, null=True) 
    fifth = models.ForeignKey('Racer', related_name='racer_fifth', on_delete=models.SET_NULL, null=True) 
    
    def get_absolute_url(self):
        return reverse('race-detail', args=[str(self.id)])
    
    def __str__(self):
        return self.name

class Comment(models.Model):
    COMMENT_TYPE = (
        ('0', 'Other'),
        ('1', 'Question about the race'),
        ('2', 'Collaboration inquiry')
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    commenter = models.ForeignKey(User, verbose_name='commenter', related_name='commenter_id', on_delete=models.SET_NULL, null=True)
    race = models.ForeignKey(Race, verbose_name='race', related_name='race_id', on_delete=models.SET_NULL, null=True) 
    text = models.CharField('Text', max_length=3000, help_text='Enter comment text')
    type = models.CharField(
        'Type',
        max_length=1,
        choices=COMMENT_TYPE,
        blank=False,
        default='0',
    )

    def __str__(self):
        return self.name

board/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Comment

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class CommentForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea, required=True)
    class Meta():
        model = Comment
        exclude = ('commenter', 'race')

board/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render
from django.views import generic

from board.models import Racer, Race, Comment
from board.forms import UserForm
from board.forms import CommentForm


def index(request):
    num_racers = Racer.objects.all().count()
    num_races = Race.objects.all().count()  
    context = {
        'num_racers': num_racers,
        'num_races': num_races,
    }
    return render(request, 'index.html', context=context)

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    context = {
        'user_form':user_form,
        'registered':registered
    }
    return render(request,'board/registration.html', context)

def races_list(request):
    races = Race.objects.all()
    context = {
        "races": races,
    }
    return render(request, 'board/races_list.html', context)

def race_detail(request, id):
    race = Race.objects.get(id=id)
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                commenter = request.user,
                race = race,
                text = form.data["text"],
                type = form.data["type"]
            )
            comment.save()
    comments = Comment.objects.filter(race=race)
    context = {
        "race": race,
        "comments": comments,
        "form": form,
    }
    return render(request, "board/race_detail.html", context)

templates/board/race_detail.html
{% extends "layout.html" %}
{% block content %}
<h1 class="mt-2">{{ race.name }}</h1>
<table class="table">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Team</th>
        <th scope="col">Vehicle</th>
        <th scope="col">Description</th>
        <th scope="col">Experience</th>
        <th scope="col">Class</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>{{ race.first.name_r }}</td>
            <td>{{ race.first.name_t }}</td>
            <td>{{ race.first.desc_c }}</td>
            <td>{{ race.first.desc_r }}</td>
            <td>{{ race.first.get_exp_r_display }}</td>
            <td>{{ race.first.get_class_r_display }}</td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>{{ race.second.name_r }}</td>
            <td>{{ race.second.name_t }}</td>
            <td>{{ race.second.desc_c }}</td>
            <td>{{ race.second.desc_r }}</td>
            <td>{{ race.second.get_exp_r_display }}</td>
            <td>{{ race.second.get_class_r_display }}</td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>{{ race.third.name_r }}</td>
            <td>{{ race.third.name_t }}</td>
            <td>{{ race.third.desc_c }}</td>
            <td>{{ race.third.desc_r }}</td>
            <td>{{ race.third.get_exp_r_display }}</td>
            <td>{{ race.third.get_class_r_display }}</td>
        </tr>
        <tr>
            <th scope="row">4</th>
            <td>{{ race.fourth.name_r }}</td>
            <td>{{ race.fourth.name_t }}</td>
            <td>{{ race.fourth.desc_c }}</td>
            <td>{{ race.fourth.desc_r }}</td>
            <td>{{ race.fourth.get_exp_r_display }}</td>
            <td>{{ race.fourth.get_class_r_display }}</td>
        </tr>
        <tr>
            <th scope="row">5</th>
            <td>{{ race.fifth.name_r }}</td>
            <td>{{ race.fifth.name_t }}</td>
            <td>{{ race.fifth.desc_c }}</td>
            <td>{{ race.fifth.desc_r }}</td>
            <td>{{ race.fifth.get_exp_r_display }}</td>
            <td>{{ race.fifth.get_class_r_display }}</td>
        </tr>
    </tbody>
</table>
<h2 class="mt-5">Comments</h2>
{% for comment in race.race_id.all %}
    <div class="card mb-1">
        <div class="card-body">
            {{ comment.text }}
        </div>
        <div class="card-footer text-muted">
            User: {{ comment.commenter }} | Type: {{ comment.get_type_display }}
        </div>
    </div>
{% endfor %}
{% if user.is_authenticated %}
<div class="card mb-5 mt-4">
    <div class="card-body">
        <h3 class="card-title">Add comment</h3>
        <form action="" method="POST">
            {% csrf_token %}
            <label for="comment_text">{{ form.text.label_tag }}</label>
            <div id="comment_text">{{ form.text }}</div>
            <label for="comment_type">{{ form.type.label_tag }}</label>
            <div id="comment_type">{{ form.type }}</div>
            <button type="submit" class="save btn btn-default mt-3">Post</button>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

templates/board/races_list.html
{% extends "layout.html" %}
{% block content %}
  <h1>Scoreboards</h1>
  <ul>
    {% for race in races %}
    <h2><a href="{{ race.get_absolute_url }}">{{ race.name }}</a></h2>
    <table class="table">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Team</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>{{ race.first.name_r }}</td>
                <td>{{ race.first.name_t }}</td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>{{ race.second.name_r }}</td>
                <td>{{ race.second.name_t }}</td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td>{{ race.third.name_r }}</td>
                <td>{{ race.third.name_t }}</td>
            </tr>
        </tbody>
    </table>
    {% endfor %}
  </ul>  
{% endblock %}

templates/board/registration.html
{% extends "layout.html" %}
{% block content %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>You're registered!</h1>
        <h2>Now you can log in.</h2>
        <a href="{% url 'login'%}?next={{request.path}}">Login</a>
      {% elif user.is_authenticated %}
        <h1>You're logged in!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        <input type="submit" name="" value="Register">
      </form>  
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/index.html
{% extends "layout.html" %}
{% block content %}
  <h1>Racing Hub</h1>
  <p>Welcome to Racing Hub!</p>
  <ul>
    <li><strong>Number of racers:</strong> {{ num_racers }}</li>
    <li><strong>Number of races:</strong> {{ num_races }}</li>
  </ul>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
  <title>Racing Hub</title>
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
        <ul class="sidebar-nav">
          {% if user.is_authenticated %}
            <li>Logged in as: {{ user.get_username }}</li>
            <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
          {% else %}
            <li><a href="{% url 'register'%}?next={{request.path}}">Register</a>
            <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
          {% endif %} 
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'races' %}">Scoreboards</a></li>
        </ul>
        {% endblock %}
      </div>
      <div class="col-sm-10 ">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>